### ISSUE TITLE
Problem: emurgis assumes everything entered is a legit problem

### ISSUE THREAD

**Issue by sjmackenzie** [EmurgoHK/Emurgis#145]
A problem should be closed if it's clearly a non-problem. Non-problems will inevitably be entered into the system, be it by a new employee learning the ropes or other more dim scenarios. Currently the final state of a legit problem is `Fixed/Solved` which does not describe the final state of a non-problem which shouldn't be solved but disregarded as soon as possible.

The process must be able to quickly isolate and disregard non-problems. Otherwise the organization spends its time doing useless nonsense. 

Solution: Possibly the simplest solution is to rename `Fixed/Solved` to `Closed`. Then allow a new (non-)problem to move directly from `Open` to `Closed` without having to go through the states `In Progress` `Ready for Review` and `Resolved`.

So the final state of a legit problem and a non-problem is `Closed`.

**Comment by gazhayes** [comment]
Non-problems can simply be deleted by a maintainer. 

There must be a distinction between closed and solved for other reasons, only problems that are ready for review can be marked as solved, a non-problem cannot be marked as solved because there was nothing to solve (and the user who "solved" it should not have this added to their statistics).

**Comment by sjmackenzie** [comment]
Ah I see, you're deferring deletion of non-problems to a level up. Fine. Though I'd argue you'd want to keep stats on users creating non-problems. Users that create a large amount of non-problems just don't get it and add friction to the system.
