### ISSUE TITLE
Why using Blaze?

### ISSUE THREAD

**Issue by Ayanrocks** [EmurgoHK/Emurgis#297]
Its not a problem but why using Blaze as template engine instead of  React.

**Comment by AshHimself** [comment]
I don't know React :D Also, all other projects are Blaze so we'd need to pretty good reason to switch IMO.

**Comment by Ayanrocks** [comment]
Ya but react is pretty fast and scalable too. With its virtual dom its faster than blaze.

**Comment by gazhayes** [comment]
Any of these projects could easily evolve under the C4 and end up using react (or whatever else), but right now the simplest solution to the problem is to use blaze. If the simplest solution to any given problem is to use react there's nothing stopping anyone from using it as a module together with blaze. If more and more problems start being easier to solve with react the simplest solution at some point may be to totally switch frameworks. The decision isn't up to us, it's up to the C4.
